### ISSUE TITLE
recording video

### ISSUE THREAD

**Issue by crosofg** [eraclitux/ipcampy#8]
How do I record video using this? I am using foscam IP camera.

**Comment by eraclitux** [comment]
Video recording is not supported :(

2016-04-19 17:30 GMT+02:00 crosofg <notifications@github.com>:

> How do I record video using this? I am using foscam IP camera.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eraclitux/ipcampy/issues/8>
>



-- 
Andrea
eraclitux.com

**Comment by crosofg** [comment]
Can you suggest any alternate means to record video streams?

**Comment by eraclitux** [comment]
Nothing actually.
